### ISSUE TITLE
add support for HmIPW-DRAP

### ISSUE THREAD

**Issue by justme-1968** [zapccu/HMCCU#116]
für den HmIPW-DRAP gibt es (zumindest in 4.3) noch keine defaults

CHN 00179D898E4DFA:0 HmIPW-DRAP 00179D898E4DFA:0
  DPT {f} HmIP-RF.00179D898E4DFA:0.ACTUAL_TEMPERATURE = 27.000000 [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.CONFIG_PENDING = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_BUS_CONFIG_MISMATCH = false [RE]
  DPT {n} HmIP-RF.00179D898E4DFA:0.ERROR_CODE = 0 [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_OVERHEAT = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_POWER_SHORT_CIRCUIT_BUS_1 = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_POWER_SHORT_CIRCUIT_BUS_2 = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_SHORT_CIRCUIT_DATA_LINE_BUS_1 = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_SHORT_CIRCUIT_DATA_LINE_BUS_2 = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.ERROR_UNDERVOLTAGE = false [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.INSTALL_TEST = true [RW]
  DPT {s} HmIP-RF.00179D898E4DFA:0.IP_ADDRESS = 10.0.1.73 [RE]
  DPT {f} HmIP-RF.00179D898E4DFA:0.OPERATING_VOLTAGE = 2.440000 [RE]
  DPT {i} HmIP-RF.00179D898E4DFA:0.OPERATING_VOLTAGE_STATUS = 0 [RE]
  DPT {b} HmIP-RF.00179D898E4DFA:0.UNREACH = false [RE]
CHN 00179D898E4DFA:1 HmIPW-DRAP 00179D898E4DFA:1
  DPT {f} HmIP-RF.00179D898E4DFA:1.CURRENT = 0.000000 [RE]
  DPT {i} HmIP-RF.00179D898E4DFA:1.CURRENT_STATUS = 0 [RE]
  DPT {f} HmIP-RF.00179D898E4DFA:1.VOLTAGE = 24.300000 [RE]
  DPT {i} HmIP-RF.00179D898E4DFA:1.VOLTAGE_STATUS = 0 [RE]
CHN 00179D898E4DFA:2 HmIPW-DRAP 00179D898E4DFA:2
  DPT {f} HmIP-RF.00179D898E4DFA:2.CURRENT = 0.000000 [RE]
  DPT {i} HmIP-RF.00179D898E4DFA:2.CURRENT_STATUS = 0 [RE]
  DPT {f} HmIP-RF.00179D898E4DFA:2.VOLTAGE = 24.300000 [RE]
  DPT {i} HmIP-RF.00179D898E4DFA:2.VOLTAGE_STATUS = 0 [RE]

**Comment by zapccu** [comment]
I would be interesting to see how this device behaves in 5.0. Because: Channel 0 doesn't have the standard role MAINTENANCE. Instead 3 channels of type ACCESSPOINT_GENERIC_RECEIVER. I guess, HMCCU will create HMCCUCHNs only for channels 1 and 2. Both devices include the datapoints from channel 0 (because it's always treated as the maintenance channel).
