### ISSUE TITLE
Lots of things changed in an incompatible way?

### ISSUE THREAD

**Issue by aski71** [zapccu/HMCCU#148]
Hi,
I experience a lot of problems since the last update a few days ago.
Data points have changed. My shades suddenly close when I use my night routine from Siri instead of opening.

Lots of error messages on the start page of fhem:

`Messages collected while initializing FHEM:configfile: ccu2: unknown attribute rpcinterval. Type 'attr ccu2 ?' for a detailed list.
ccu2: unknown attribute rpcport. Type 'attr ccu2 ?' for a detailed list.
Hauptlicht: unknown attribute ccureadings. Type 'attr Hauptlicht ?' for a detailed list.
Sideboard: unknown attribute ccureadings. Type 'attr Sideboard ?' for a detailed list.
Vitrine: unknown attribute ccureadings. Type 'attr Vitrine ?' for a detailed list.
Multimedia: unknown attribute ccureadings. Type 'attr Multimedia ?' for a detailed list.
MultimediaSurround: unknown attribute ccureadings. Type 'attr MultimediaSurround ?' for a detailed list.
FritzDECT2: unknown attribute ccureadings. Type 'attr FritzDECT2 ?' for a detailed list.
BadSpiegel: unknown attribute ccureadings. Type 'attr BadSpiegel ?' for a detailed list.
BadDecke: unknown attribute ccureadings. Type 'attr BadDecke ?' for a detailed list.
BewegungBad: unknown attribute ccureadings. Type 'attr BewegungBad ?' for a detailed list.
HMCCUDEV [BewegungBad] Value of attribute statedatapoint must be in format channel.datapoint
FritzDECT1: unknown attribute ccureadings. Type 'attr FritzDECT1 ?' for a detailed list.
HMCCUDEV [Wandthermostat] Value of attribute statedatapoint must be in format channel.datapoint
HMCCUDEV [Thermostat] Value of attribute statedatapoint must be in format channel.datapoint
SonosKueche: unknown attribute ccureadings. Type 'attr SonosKueche ?' for a detailed list.
SonosDuschbad: unknown attribute ccureadings. Type 'attr SonosDuschbad ?' for a detailed list.
WohnzimmerCam: unknown attribute ccureadings. Type 'attr WohnzimmerCam ?' for a detailed list.
SchlafzimmerCam: unknown attribute ccureadings. Type 'attr SchlafzimmerCam ?' for a detailed list.
KuechenCam: unknown attribute ccureadings. Type 'attr KuechenCam ?' for a detailed list.
BueroLicht: unknown attribute ccureadings. Type 'attr BueroLicht ?' for a detailed list.
BewegungDuschbad: unknown attribute ccureadings. Type 'attr BewegungDuschbad ?' for a detailed list.
HMCCUDEV [BewegungDuschbad] Value of attribute statedatapoint must be in format channel.datapoint
LichtschalterFlurTuer: unknown attribute ccureadings. Type 'attr LichtschalterFlurTuer ?' for a detailed list.
LichtschalterFlurWZ: unknown attribute ccureadings. Type 'attr LichtschalterFlurWZ ?' for a detailed list.
FlurLicht: unknown attribute ccureadings. Type 'attr FlurLicht ?' for a detailed list.
Duschbad: unknown attribute ccureadings. Type 'attr Duschbad ?' for a detailed list.
KuecheLicht: unknown attribute ccureadings. Type 'attr KuecheLicht ?' for a detailed list.
KuecheKleinLicht: unknown attribute ccureadings. Type 'attr KuecheKleinLicht ?' for a detailed list.
SZDimmer: unknown attribute ccureadings. Type 'attr SZDimmer ?' for a detailed list.
HMCCUDEV [SZDimmer] Value of attribute statedatapoint must be in format channel.datapoint
Badradio: unknown attribute ccureadings. Type 'attr Badradio ?' for a detailed list.
Zierlicht: unknown attribute ccureadings. Type 'attr Zierlicht ?' for a detailed list.
SLichterkette: unknown attribute ccureadings. Type 'attr SLichterkette ?' for a detailed list.
MMSchlafzimmer: unknown attribute ccureadings. Type 'attr MMSchlafzimmer ?' for a detailed list.
Balkonlicht: unknown attribute ccureadings. Type 'attr Balkonlicht ?' for a detailed list.
Helligkeitssensor: unknown attribute ccureadings. Type 'attr Helligkeitssensor ?' for a detailed list.
HMCCUDEV [Helligkeitssensor] Value of attribute statedatapoint must be in format channel.datapoint
BewegungKueche: unknown attribute ccureadings. Type 'attr BewegungKueche ?' for a detailed list.
HMCCUDEV [BewegungKueche] Value of attribute statedatapoint must be in format channel.datapoint
BewegungWohnen: unknown attribute ccureadings. Type 'attr BewegungWohnen ?' for a detailed list.
HMCCUDEV [BewegungWohnen] Value of attribute statedatapoint must be in format channel.datapoint
B_Presence: unknown attribute ccureadings. Type 'attr B_Presence ?' for a detailed list.
HMCCUDEV [B_Presence] Value of attribute statedatapoint must be in format channel.datapoint
Kuechenzeile: unknown attribute ccureadings. Type 'attr Kuechenzeile ?' for a detailed list.
CatDetector: unknown attribute ccureadings. Type 'attr CatDetector ?' for a detailed list.
HMCCUDEV [CatDetector] Value of attribute statedatapoint`

The LEVEL data point of a HM-LC-Bl1-SM suddenly only shows open and closed instead of the numeric amount.
Also my "control" redefinition via widgetOverride for HM-LC-Bl1-SM and dimmer HM-LC-Dim1TPBU-FM is broken.

What's going on?
This is a huge setback and loss of funcionality.
Frustrating.

**Comment by zapccu** [comment]
Regarding the error messages in the log: Most of them are related to attributes which are no longer needed / supported.
The attribute rpcinterval is a leftover from a very old HMCCU version, which was using the internal RPC server.
The attribute ccureadings has been removed in 5.0.
Please save the FHEM config and start FHEM again. The new config won't contain the unsupported attributes any more.

Regarding messages "Value of attribute statedatapoint must be in format channel.datapoint". This has never worked, even in 4.3. But now HMCCU is handling this error correctly. If you set "statedatapoint" or "controldatapoint" in a HMCCUDEV device, it must be in format channelNumber.datapointName. i.e. "1.STATE" or "2.LEVEL". Many device types don't need these attributes any more. You can try "set defaults reset" or "set defaults forceReset" for these devices, i.e. "set Helligkeitssensor defaults forceReset". Otherwise simply set "statedatapoint" again in WebUI and select a valid datapoint.

Also for the HM-LC-Bl1-SM it might be a good idea to reset the defaults.

After you made these changes restart FHEM. If it's still not working, send me a list of the affected devices.

**Comment by aski71** [comment]
Thanks!
Saving fhem.cfg and restarting solved the above messages in the fhem home screen.
"set defaults reset" also worked for the affected devices.
Needed to modify homebridgemapping as well.
Can widgetOverride still be used? I'd rather have a knob again than the sliders.

**Comment by zapccu** [comment]
Sure, feel free to modify any FHEM standard attribute like "widgetOverride". If you modify it and use "set defaults reset" later, HMCCU won't touch any attribute which differs from the old 4.3 defaults. You will get a hint, which attributes can be modified or removed. 
If you use "set defaults forceReset", HMCCU will ignore / override your changes.
