### ISSUE TITLE
CuXD devices not working anymore

### ISSUE THREAD

**Issue by aski71** [zapccu/HMCCU#167]
Hi,
another issue since the last update: I can't switch some of my CuXD devices anymore.
I configured some FritzDECT power outlets via CuXD. Now I can't switch them on or off.

Here's an example which worked before:

`# FritzDECT1
define FritzDECT1 HMCCUCHN CUX2801005:1
setuuid FritzDECT1 5c4afdb8-f33f-2248-361a-5cf984e924436f21
attr FritzDECT1 IODev ccu2
attr FritzDECT1 alias MusikEcke
attr FritzDECT1 ccureadingfilter (STATE|ON_TIME)
attr FritzDECT1 devStateIcon on:message_socket_enabled@green off:message_socket_disabled@black Initialized:message_socket_unknown@red
attr FritzDECT1 event-on-change-reading .*
attr FritzDECT1 fp_Home3D 523,360,0,FritzDECT1
attr FritzDECT1 genericDeviceType switch
attr FritzDECT1 homebridgeMapping On=state,valueOn=on,valueOff=off Brightness=clear
attr FritzDECT1 room Büro,HomekitActors
attr FritzDECT1 siriName MusikEcke
attr FritzDECT1 statedatapoint STATE
attr FritzDECT1 statevals on:true,off:false
attr FritzDECT1 substitute STATE!true:on,false:off,1:on,0:off`

I tried the solution you gave for the blinds and used a "defaults reset" and "defaults forceReset", but it doesn't help either.
Output of the command is:

`HMCCUCHN: Balkonlicht Device type HM-LC-Sw1-Pl not known by HMCCU
Cannot detect role of MusikEcke
No version 4.3 default attributes found`

Thanks again for help.

**Comment by aski71** [comment]
Any help on this one?
Thanks!

**Comment by zapccu** [comment]
Which device type (2 digit number) did you use when creating the devices in CUxD?

**Comment by aski71** [comment]
Fun fact: Since the last reboot of the machine it's working again. shutdown restart did not solve the problem before, though. Strange. Thanks anyway.

**Comment by zapccu** [comment]
I fixed an error in device detection with the update yesterday. An update to this version is highly recommended. In the previous version (the one you are running) it's a coincidence whether a device is working or not after a restart of FHEM.
