### ISSUE TITLE
HM-Sec-Win not working anymore

### ISSUE THREAD

**Issue by aski71** [zapccu/HMCCU#174]
I now found out my HM-Sec-Win is also no longer operable.
I don't find a solution. Tried defaults reset and forcereset, as well update and old.

`define KMotorfenster HMCCUDEV MEQ1471077
setuuid KMotorfenster 5c4afdbc-f33f-2248-7fab-252481083958c8bb
attr KMotorfenster IODev ccu2
attr KMotorfenster alias KMotorfenster
attr KMotorfenster cmdIcon tilt:fts_window_1w_tilt@black lock:fts_window_1w@black close:fts_window_1w@red
attr KMotorfenster controldatapoint 1.LEVEL
attr KMotorfenster devStateIcon -0.005000:fts_window_1w@green 0.000000:fts_window_1w@red .*:fts_window_1w_tilt@yellow
attr KMotorfenster eventMap tilt:1.0 lock:-0.005 close:0.000000
attr KMotorfenster fp_Home3D 662,914,5,Küchenfenster
attr KMotorfenster genericDeviceType window
attr KMotorfenster homebridgeMapping CurrentPosition=siriValue,minValue=0,maxValue=100,minStep=1 TargetPosition=control,factor=100,minValue=0,maxValue=100,minStep=1,delay=2,cmds=0:lock,cmd=control PositionState=1.DIRECTION,values=0:STOPPED;;2:DECREASING;;1:INCREASING
attr KMotorfenster room HomekitActors,Küche
attr KMotorfenster siriName Küche Motorfenster
attr KMotorfenster statechannel 1
attr KMotorfenster statedatapoint 1.LEVEL
attr KMotorfenster statevals lock:-0.005,tilt:1.0,close:0.000000
attr KMotorfenster userReadings Battery:2.LEVEL.* { ReadingsVal("KMotorfenster","2.LEVEL","error")*100 },siriValue:1.LEVEL.* { my $windowstate = ReadingsVal("KMotorfenster","1.LEVEL","error");; return 0.0 if $windowstate < 0;; return $windowstate*100;; }
attr KMotorfenster webCmd tilt:close:lock
`

When I try the tilt command it now says: 
`Unknown argument tilt choose one of clear defaults:reset,update,old,forceReset readingFilter:multiple-strict,0.AES_KEY,0.CONFIG_PENDING,0.DUTYCYCLE,0.LOWBAT,0.RSSI_DEVICE,0.RSSI_PEER,0.STICKY_UNREACH,0.UNREACH,1.DIRECTION,1.ERROR,1.INHIBIT,1.LEVEL,1.STATE_UNCERTAIN,1.WORKING,2.LEVEL,2.STATUS config datapoint close:noArg open:noArg toggle:noArg `

**Comment by zapccu** [comment]
Introduced new flag "noBoundsChecking" for attribute ccuflags. 
Added support for role WINMATIC.
Commands:
set open
set close
set lock
set pct
