### ISSUE TITLE
Add support for Filllevel Sensor HM-Sen-Wa-Od

### ISSUE THREAD

**Issue by bublath** [zapccu/HMCCU#183]
Device channels and datapoints

DEV HM-Sen-Wa-Od PEQxxxxxxx PEQxxxxxxx interface=BidCos-RF type=HM-Sen-Wa-Od
CHN PEQxxxxxxx:0 HM-Sen-Wa-Od PEQxxxxxxx:0
   0.UNREACH = false {b} [RE]
   0.STICKY_UNREACH = false {b} [RWE]
   0.CONFIG_PENDING = false {b} [RE]
   0.LOWBAT = true {b} [RE]
   0.RSSI_DEVICE = 1 {n} [RE]
   0.RSSI_PEER = 185 {n} [RE]
   0.DEVICE_IN_BOOTLOADER = false {b} [RE]
   0.UPDATE_PENDING = false {b} [RE]
   0.AES_KEY = 0 {n} [R]
CHN PEQxxxxxxx:1 HM-Sen-Wa-Od PEQxxxxxxx:1
   1.FILLING_LEVEL = 91 {i} [RE]
   1.INSTALL_TEST =  {b} [E]

Device detection:
No state datapoint detected
No control datapoint detected

Failed to detect device settings. Device must be configured manually.

Current state datapoint = 1.FILLING_LEVEL

Current control datapoint = .

Device description

Device PEQxxxxxxx HM-Sen-Wa-Od PEQxxxxxxx [HM-Sen-Wa-Od]
  CHILDREN: PEQxxxxxxx:0,PEQxxxxxxx:1
  FIRMWARE: 1.3
  FLAGS: Visible
  INTERFACE: PEQ0531159
  PARAMSETS: MASTER
  RF_ADDRESS: 7032494
  ROAMING: 0
  RX_MODE: ALWAYS,LAZY_CONFIG
  UPDATABLE: 1
Channel PEQxxxxxxx:0 HM-Sen-Wa-Od PEQxxxxxxx:0 [MAINTENANCE]
  AES_ACTIVE: 0
  DIRECTION: NONE
  FLAGS: Visible,Internal
  PARAMSETS: MASTER,VALUES
  PARENT: PEQxxxxxxx
  PARENT_TYPE: HM-Sen-Wa-Od
Channel PEQxxxxxxx:1 HM-Sen-Wa-Od PEQxxxxxxx:1 [CAPACITIVE_FILLING_LEVEL_SENSOR]
  AES_ACTIVE: 0
  DIRECTION: SENDER
  FLAGS: Visible
  LINK_SOURCE_ROLES: WEATHER_CS
  PARAMSETS: LINK,MASTER,VALUES
  PARENT: PEQxxxxxxx
  PARENT_TYPE: HM-Sen-Wa-Od

Defaults

**Comment by zapccu** [comment]
Added role CAPACITIVE_FILLING_LEVEL_SENSOR.

Command "get createDev" will create 1 HMCCUCHN device for channel 1. Fill level is stored in reading "level".
