### ISSUE TITLE
Authentication for Rega access is not working

### ISSUE THREAD

**Issue by zapccu** [zapccu/HMCCU#209]
Forum: https://forum.fhem.de/index.php/topic,125283.msg1199378.html#msg1199378

**Comment by ntinti** [comment]
Does work now. Thanks a lot.
Btw. The authentication data is written to the log file in cleartext, e.g:
`Registering callback http://192.168.0.1:7411/fh2001 of type A with ID CB2001044049044097 at http://Admin:geheim@192.168.0.2:2001`
Imho there shouldn't be any passwords in the log.

**Comment by ntinti** [comment]
But now again,  there are no actual  data coming in via the RPC Server - with authentication and without.

**Comment by zapccu** [comment]
Not reproducible any more. Credentials are removed from log and authentication is working.
